global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'telegram-streaming-app'
    static_configs:
      - targets: ['telegram-streaming-app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  - job_name: 'tdlib-service'
    static_configs:
      - targets: ['tdlib-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'webrtc-bridge'
    static_configs:
      - targets: ['webrtc-bridge:8081']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s