version: '3.8'

services:
  tdlib-service:
    build:
      context: .
      dockerfile: Dockerfile.tdlib
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    volumes:
      - tdlib_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  webrtc-bridge:
    build:
      context: .
      dockerfile: Dockerfile.webrtc
    ports:
      - "8081:8081"
    environment:
      - FFMPEG_THREADS=4
      - MAX_CONCURRENT_STREAMS=10
    restart: unless-stopped
    depends_on:
      - tdlib-service

volumes:
  tdlib_data: